.goreleaser.yml
csp_collector.go

Sometimes you want to know what is going on under the hood without breaking
out a debugger. Other times you really don't care. To facilitate both of
these needs, I've created a `debug` logger that will handle outputting it
correctly and conditionally outputted it based on the flags at runtime.
In this PR, I'm also experimenting with [`goreleaser`](https://github.com/goreleaser/goreleaser) to handle the
distribution of packages better.

Add `-debug` flag

---

.travis.yml
csp_collector.go

- `deposition`
- `script_sample`
- `status_code`
Converts all hyphens to underscores in the output due to some parser
issues where hyphens are mislabelled.

Adds more violation report fields

---

csp_collector.go
csp_collector_test.go

Updates the `CSPReport` struct to accept a string or integer for the
`status-code` value due to browser inconsistencies in violation reports.
As a side note, I'm chasing up which browsers are sending strings as
CSP2 and CSP3 expect a `long` and `int` respectively.
Fixes #15

Allow `status-code` to be string or integer

---

.travis.yml
go.mod
go.sum

Updates the library to rely on `go mod` instead of custom vendoring for
the dependency management.
Fixes #14

Add support for `go mod`

---

csp_collector.go
csp_collector_test.go
sample.filterlist.txt

Allow lines starting with a "#" to be treated as comments in the filter list.
Add a relevant example to the sample list.
Add a test for the functionality.

Allow comments in filter list

---

.gitignore
script/build

Create some automation around building release assets instead of manually
doing it each time.

Add `script/build` script for generating binaries and tarballs

---

csp_collector.go
csp_collector_test.go

Standard reports will include the uri of the document they're sent from. Some
browsers will get confused though and send reports for either empty or bogus
documents like "about". These are not actionable and can be excluded from
reporting.

Exclude non-http documents

---

README.md
csp_collector.go
csp_collector_test.go

This allows services to add some data which can be correlated with a specific
request without trying to match specific time/url/... by hand in the logs.
Any string assigned to first `metadata` parameter will be copied verbatim to the
logged `metadata` field.

Support injecting metadata as new field

---

script/build

Fixes the build script to only tarball the executable instead of the
build directory too.
Includes a fix to pass through `Rev` for the `-version` output (
`version + build metadata` of git sha).

Update build script to ignore structure

---

csp_collector.go
sample.filterlist.txt

These are used for the universal ms apps.
Ref: https://docs.microsoft.com/en-us/windows/uwp/app-resources/uri-schemes#ms-appx-and-ms-appx-web

Ignore the ms-appx schemas

---

README.md
csp_collector.go

Health check urls aren't really standardized - many use healthz but just as many use completely custom endpoints.
Having a command line option to change this url adds some flexibility when deploying this application without provided helm chart.

Add flag to change healthcheck url

---

deployments/systemd/go-csp-collector.service

Add a systemd unit file to run the go-csp-collector as a sandboxed
service with the fewest privileges possible. "systemd-analyze security"
gives this unit a score of "0.9 SAFE".

Add a systemd unit file

---

deployments/kubernetes-helm/templates/deployment.yaml

Useful when you want to explicitly set the 'run as user', for example.

Allow setting a securityContext

---

deployments/kubernetes-helm/templates/service.yaml

The selectors aren't referencing the deployment, using the intended helper should do the trick

Fix selector in service: use helper function

---

deployments/kubernetes-helm/templates/ingress.yaml

extensions/v1beta1 is removed in v1.22, so suggesting to change it to networking.k8s.io/v1 which is supported from v1.19

Bump ingress apiVersion (kubernetes v1.19+)

---

.github/workflows/lint.yml
.github/workflows/test.yml
Dockerfile
README.md
csp_collector.go
csp_collector_test.go

For our use case, we want do log additional information about a CSP report.
This change should be backwards-compatible:
* The `path` field is new, but in structured logging and in JSON additional fields should not be a problem.
* Client IP logging is disabled by default, as client IP is considerered sensitive data. Logging it should be opt-in.
* In certain use cases, the query string or the fragment part (if transmitted by the browser) might contain sensitive data, which might no be needed to act on the report. Thus, it shouldn't be logged at all.

Log more interesting information

---

Dockerfile

Thanks for this great project!  I started putting it in our app and when I pulled it down, I wasn't able to build the Dockerfile:
```
❯ docker build .
[+] Building 5.4s (10/13)
=> [internal] load build definition from Dockerfile                                                        0.0s
=> => transferring dockerfile: 37B                                                                         0.0s
=> [internal] load .dockerignore                                                                           0.0s
=> => transferring context: 34B                                                                            0.0s
=> [internal] load metadata for docker.io/library/alpine:3.16                                              1.1s
=> [internal] load metadata for …
```

Fix Dockerfile to build binary

---

script/build

Hey, thanks for merging #75 so quickly!  As I'm continuing getting this setup for us, we'd love ARM builds for our developer machines.  Is this an addition that you're interested in?  I saw that you had `script/build` setup in a way that made this trivial to add, but I suspect there might be other considerations here too.
Thoughts on this change and including ARM builds with the binary releases?

Add arm64 targets for Linux and Darwin

---

deployments/kubernetes-helm/templates/_helpers.tpl
deployments/kubernetes-helm/templates/deployment.yaml
deployments/kubernetes-helm/templates/hpa.yaml
deployments/kubernetes-helm/templates/serviceaccount.yaml
deployments/kubernetes-helm/values.yaml

Hi, I needed a way to configure imagePullSecrets and securityContext related stuff and ended up updating the entire chart to fit what's generated nowadays with helm create. 
This adds a ServiceAccount, HPA and some options to further configure the Deployment, this could be split up into multiple PRs if needed.
Cheers

update chart to reflect current standards

---

.github/workflows/build.yml
.github/workflows/build_image.yml

Automate the build and provisioning of docker images to the `jacobbednarz/go-csp-collector` docker hub repo.
As discussed in https://github.com/jacobbednarz/go-csp-collector/issues/90, a new multi-arch image is now built when a new release is done (or a git tag is pushed manually). 
For this to work two conditions have to be fulfilled:
1. As already mentioned in the issue, the two repository secrets `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` have to be present for the action.
2. A release Github release has to be based on a tag (or a corresponding tag has to be pushed manually).
Open for any suggestions/improvements.

Build and push multi-arch docker images

---

README.md
internal/handler/csp.go
internal/handler/csp_test.go

Add [source-file](https://www.w3.org/TR/CSP3/#violation-source-file) and associated column-number and line-number.
Also fix build command in README and change `-` to `_` for consistency with Dockerfile.
Fixes #94.
I don't actually program in go, but I can copy and paste and change text. It passes `go test` and in a live test comes out in Grafana as follows:

Add source-file and associated column-number and line-number.

---

.gitignore
README.md
go.mod
go.sum
internal/handler/report_api_csp.go
internal/handler/report_api_csp_test.go
internal/utils/utils.go
main.go

Added the CSP reporting API (as the "report-uri" was deprecated).
Closes #67

feat: added new CSP endpoint for reporting API
